doctrine_migrations:
    migrations_paths: 
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
   
    # migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        # 
    #dir_name: 
        # '%kernel.project_dir%/migrations'
    #namespace: DoctrineMigrations

